services:
  crud-csvapp:
    container_name: crud-csv-app-container
    build: .
    image: crud-csv-app:latest
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
